//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Web.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarRental.Web.Localization.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compact.
        /// </summary>
        public static string Category_C {
            get {
                return ResourceManager.GetString("Category_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compact Elite.
        /// </summary>
        public static string Category_D {
            get {
                return ResourceManager.GetString("Category_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Economy.
        /// </summary>
        public static string Category_E {
            get {
                return ResourceManager.GetString("Category_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullsize.
        /// </summary>
        public static string Category_F {
            get {
                return ResourceManager.GetString("Category_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullsize Elite.
        /// </summary>
        public static string Category_G {
            get {
                return ResourceManager.GetString("Category_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Economy Elite.
        /// </summary>
        public static string Category_H {
            get {
                return ResourceManager.GetString("Category_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate.
        /// </summary>
        public static string Category_I {
            get {
                return ResourceManager.GetString("Category_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate Elite.
        /// </summary>
        public static string Category_J {
            get {
                return ResourceManager.GetString("Category_J", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luxury.
        /// </summary>
        public static string Category_L {
            get {
                return ResourceManager.GetString("Category_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mini.
        /// </summary>
        public static string Category_M {
            get {
                return ResourceManager.GetString("Category_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mini Elite.
        /// </summary>
        public static string Category_N {
            get {
                return ResourceManager.GetString("Category_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oversize.
        /// </summary>
        public static string Category_O {
            get {
                return ResourceManager.GetString("Category_O", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium.
        /// </summary>
        public static string Category_P {
            get {
                return ResourceManager.GetString("Category_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Elite.
        /// </summary>
        public static string Category_R {
            get {
                return ResourceManager.GetString("Category_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string Category_S {
            get {
                return ResourceManager.GetString("Category_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium Elite.
        /// </summary>
        public static string Category_U {
            get {
                return ResourceManager.GetString("Category_U", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luxury Elite.
        /// </summary>
        public static string Category_W {
            get {
                return ResourceManager.GetString("Category_W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special.
        /// </summary>
        public static string Category_X {
            get {
                return ResourceManager.GetString("Category_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beige.
        /// </summary>
        public static string Color_Beige {
            get {
                return ResourceManager.GetString("Color_Beige", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string Color_Black {
            get {
                return ResourceManager.GetString("Color_Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string Color_Blue {
            get {
                return ResourceManager.GetString("Color_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brown.
        /// </summary>
        public static string Color_Brown {
            get {
                return ResourceManager.GetString("Color_Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold.
        /// </summary>
        public static string Color_Gold {
            get {
                return ResourceManager.GetString("Color_Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray.
        /// </summary>
        public static string Color_Gray {
            get {
                return ResourceManager.GetString("Color_Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string Color_Green {
            get {
                return ResourceManager.GetString("Color_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        public static string Color_Orange {
            get {
                return ResourceManager.GetString("Color_Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        public static string Color_Purple {
            get {
                return ResourceManager.GetString("Color_Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string Color_Red {
            get {
                return ResourceManager.GetString("Color_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver.
        /// </summary>
        public static string Color_Silver {
            get {
                return ResourceManager.GetString("Color_Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string Color_White {
            get {
                return ResourceManager.GetString("Color_White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string Color_Yellow {
            get {
                return ResourceManager.GetString("Color_Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Common_Add {
            get {
                return ResourceManager.GetString("Common_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Common_Apply {
            get {
                return ResourceManager.GetString("Common_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Common_Clear {
            get {
                return ResourceManager.GetString("Common_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Common_Header_Actions {
            get {
                return ResourceManager.GetString("Common_Header_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed..
        /// </summary>
        public static string Common_OperationFailed {
            get {
                return ResourceManager.GetString("Common_OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Day_Friday {
            get {
                return ResourceManager.GetString("Day_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Day_Monday {
            get {
                return ResourceManager.GetString("Day_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Day_Saturday {
            get {
                return ResourceManager.GetString("Day_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Day_Sunday {
            get {
                return ResourceManager.GetString("Day_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Day_Thursday {
            get {
                return ResourceManager.GetString("Day_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Day_Tuesday {
            get {
                return ResourceManager.GetString("Day_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Day_Wednesday {
            get {
                return ResourceManager.GetString("Day_Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydrogen, A/C.
        /// </summary>
        public static string Fuel_A {
            get {
                return ResourceManager.GetString("Fuel_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydrogen, no A/C.
        /// </summary>
        public static string Fuel_B {
            get {
                return ResourceManager.GetString("Fuel_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric.
        /// </summary>
        public static string Fuel_C {
            get {
                return ResourceManager.GetString("Fuel_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diesel, A/C.
        /// </summary>
        public static string Fuel_D {
            get {
                return ResourceManager.GetString("Fuel_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric.
        /// </summary>
        public static string Fuel_E {
            get {
                return ResourceManager.GetString("Fuel_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-fuel, no A/C.
        /// </summary>
        public static string Fuel_F {
            get {
                return ResourceManager.GetString("Fuel_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybrid.
        /// </summary>
        public static string Fuel_H {
            get {
                return ResourceManager.GetString("Fuel_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plug-in Hybrid.
        /// </summary>
        public static string Fuel_I {
            get {
                return ResourceManager.GetString("Fuel_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LPG/CNG, A/C.
        /// </summary>
        public static string Fuel_L {
            get {
                return ResourceManager.GetString("Fuel_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-fuel, A/C.
        /// </summary>
        public static string Fuel_M {
            get {
                return ResourceManager.GetString("Fuel_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified, no A/C.
        /// </summary>
        public static string Fuel_N {
            get {
                return ResourceManager.GetString("Fuel_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diesel, no A/C.
        /// </summary>
        public static string Fuel_Q {
            get {
                return ResourceManager.GetString("Fuel_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified, A/C.
        /// </summary>
        public static string Fuel_R {
            get {
                return ResourceManager.GetString("Fuel_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LPG/CNG, no A/C.
        /// </summary>
        public static string Fuel_S {
            get {
                return ResourceManager.GetString("Fuel_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethanol, A/C.
        /// </summary>
        public static string Fuel_U {
            get {
                return ResourceManager.GetString("Fuel_U", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petrol, A/C.
        /// </summary>
        public static string Fuel_V {
            get {
                return ResourceManager.GetString("Fuel_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethanol, no A/C.
        /// </summary>
        public static string Fuel_X {
            get {
                return ResourceManager.GetString("Fuel_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petrol, no A/C.
        /// </summary>
        public static string Fuel_Z {
            get {
                return ResourceManager.GetString("Fuel_Z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add location.
        /// </summary>
        public static string Locations_Add {
            get {
                return ResourceManager.GetString("Locations_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string Locations_Closed {
            get {
                return ResourceManager.GetString("Locations_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location created..
        /// </summary>
        public static string Locations_Created {
            get {
                return ResourceManager.GetString("Locations_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete location &quot;{0}&quot;? This cannot be undone..
        /// </summary>
        public static string Locations_DeleteConfirm {
            get {
                return ResourceManager.GetString("Locations_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location deleted..
        /// </summary>
        public static string Locations_Deleted {
            get {
                return ResourceManager.GetString("Locations_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete holiday {0} ({1})?.
        /// </summary>
        public static string Locations_DeleteHolidayConfirm {
            get {
                return ResourceManager.GetString("Locations_DeleteHolidayConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete location.
        /// </summary>
        public static string Locations_DeleteLocation {
            get {
                return ResourceManager.GetString("Locations_DeleteLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add location.
        /// </summary>
        public static string Locations_DialogTitle_Add {
            get {
                return ResourceManager.GetString("Locations_DialogTitle_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add holiday.
        /// </summary>
        public static string Locations_DialogTitle_AddHoliday {
            get {
                return ResourceManager.GetString("Locations_DialogTitle_AddHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete location.
        /// </summary>
        public static string Locations_DialogTitle_Delete {
            get {
                return ResourceManager.GetString("Locations_DialogTitle_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete holiday.
        /// </summary>
        public static string Locations_DialogTitle_DeleteHoliday {
            get {
                return ResourceManager.GetString("Locations_DialogTitle_DeleteHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit location.
        /// </summary>
        public static string Locations_DialogTitle_Edit {
            get {
                return ResourceManager.GetString("Locations_DialogTitle_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit location.
        /// </summary>
        public static string Locations_EditLocation {
            get {
                return ResourceManager.GetString("Locations_EditLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Locations_Field_Address {
            get {
                return ResourceManager.GetString("Locations_Field_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed all day.
        /// </summary>
        public static string Locations_Field_ClosedAllDay {
            get {
                return ResourceManager.GetString("Locations_Field_ClosedAllDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed on this day.
        /// </summary>
        public static string Locations_Field_ClosedThisDay {
            get {
                return ResourceManager.GetString("Locations_Field_ClosedThisDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes.
        /// </summary>
        public static string Locations_Field_Closes {
            get {
                return ResourceManager.GetString("Locations_Field_Closes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Locations_Field_Date {
            get {
                return ResourceManager.GetString("Locations_Field_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday name (optional).
        /// </summary>
        public static string Locations_Field_HolidayName {
            get {
                return ResourceManager.GetString("Locations_Field_HolidayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Locations_Field_Latitude {
            get {
                return ResourceManager.GetString("Locations_Field_Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Locations_Field_Longitude {
            get {
                return ResourceManager.GetString("Locations_Field_Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Locations_Field_Name {
            get {
                return ResourceManager.GetString("Locations_Field_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens.
        /// </summary>
        public static string Locations_Field_Opens {
            get {
                return ResourceManager.GetString("Locations_Field_Opens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday added..
        /// </summary>
        public static string Locations_HolidayAdded {
            get {
                return ResourceManager.GetString("Locations_HolidayAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday deleted..
        /// </summary>
        public static string Locations_HolidayDeleted {
            get {
                return ResourceManager.GetString("Locations_HolidayDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holidays.
        /// </summary>
        public static string Locations_Holidays {
            get {
                return ResourceManager.GetString("Locations_Holidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working hours updated..
        /// </summary>
        public static string Locations_HoursUpdated {
            get {
                return ResourceManager.GetString("Locations_HoursUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Locations_Inactive {
            get {
                return ResourceManager.GetString("Locations_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No holidays defined..
        /// </summary>
        public static string Locations_NoHolidays {
            get {
                return ResourceManager.GetString("Locations_NoHolidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickup locations.
        /// </summary>
        public static string Locations_Title {
            get {
                return ResourceManager.GetString("Locations_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location updated..
        /// </summary>
        public static string Locations_Updated {
            get {
                return ResourceManager.GetString("Locations_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working hours.
        /// </summary>
        public static string Locations_WorkingHours {
            get {
                return ResourceManager.GetString("Locations_WorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Nav_Home {
            get {
                return ResourceManager.GetString("Nav_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        public static string Nav_Locations {
            get {
                return ResourceManager.GetString("Nav_Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Nav_Login {
            get {
                return ResourceManager.GetString("Nav_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Nav_Logout {
            get {
                return ResourceManager.GetString("Nav_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturers.
        /// </summary>
        public static string Nav_Manufacturers {
            get {
                return ResourceManager.GetString("Nav_Manufacturers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rentals.
        /// </summary>
        public static string Nav_Rentals {
            get {
                return ResourceManager.GetString("Nav_Rentals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservations.
        /// </summary>
        public static string Nav_Reservations {
            get {
                return ResourceManager.GetString("Nav_Reservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicles.
        /// </summary>
        public static string Nav_Vehicles {
            get {
                return ResourceManager.GetString("Nav_Vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel reservation.
        /// </summary>
        public static string Reservations_Action_Cancel {
            get {
                return ResourceManager.GetString("Reservations_Action_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Reservations_Action_Confirm {
            get {
                return ResourceManager.GetString("Reservations_Action_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark no-show.
        /// </summary>
        public static string Reservations_Action_NoShow {
            get {
                return ResourceManager.GetString("Reservations_Action_NoShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New reservation.
        /// </summary>
        public static string Reservations_Add {
            get {
                return ResourceManager.GetString("Reservations_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel reservation #{0}?.
        /// </summary>
        public static string Reservations_CancelConfirm {
            get {
                return ResourceManager.GetString("Reservations_CancelConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation cancelled..
        /// </summary>
        public static string Reservations_Cancelled {
            get {
                return ResourceManager.GetString("Reservations_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation confirmed..
        /// </summary>
        public static string Reservations_Confirmed {
            get {
                return ResourceManager.GetString("Reservations_Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation created..
        /// </summary>
        public static string Reservations_Created {
            get {
                return ResourceManager.GetString("Reservations_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer ID (staff only, optional).
        /// </summary>
        public static string Reservations_Field_Customer {
            get {
                return ResourceManager.GetString("Reservations_Field_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropoff location.
        /// </summary>
        public static string Reservations_Field_DropoffLocation {
            get {
                return ResourceManager.GetString("Reservations_Field_DropoffLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickup location.
        /// </summary>
        public static string Reservations_Field_PickupLocation {
            get {
                return ResourceManager.GetString("Reservations_Field_PickupLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickup time.
        /// </summary>
        public static string Reservations_Field_PickupTime {
            get {
                return ResourceManager.GetString("Reservations_Field_PickupTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return time.
        /// </summary>
        public static string Reservations_Field_ReturnTime {
            get {
                return ResourceManager.GetString("Reservations_Field_ReturnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        public static string Reservations_Field_Vehicle {
            get {
                return ResourceManager.GetString("Reservations_Field_Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Reservations_Filter_Status {
            get {
                return ResourceManager.GetString("Reservations_Filter_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        public static string Reservations_Filter_Vehicle {
            get {
                return ResourceManager.GetString("Reservations_Filter_Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost (€).
        /// </summary>
        public static string Reservations_Header_Cost {
            get {
                return ResourceManager.GetString("Reservations_Header_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Reservations_Header_Customer {
            get {
                return ResourceManager.GetString("Reservations_Header_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        public static string Reservations_Header_Locations {
            get {
                return ResourceManager.GetString("Reservations_Header_Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickup.
        /// </summary>
        public static string Reservations_Header_Pickup {
            get {
                return ResourceManager.GetString("Reservations_Header_Pickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string Reservations_Header_Return {
            get {
                return ResourceManager.GetString("Reservations_Header_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Reservations_Header_Status {
            get {
                return ResourceManager.GetString("Reservations_Header_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        public static string Reservations_Header_Vehicle {
            get {
                return ResourceManager.GetString("Reservations_Header_Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation marked as no-show..
        /// </summary>
        public static string Reservations_MarkedNoShow {
            get {
                return ResourceManager.GetString("Reservations_MarkedNoShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No reservations found..
        /// </summary>
        public static string Reservations_NoData {
            get {
                return ResourceManager.GetString("Reservations_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark reservation #{0} as no-show?.
        /// </summary>
        public static string Reservations_NoShowConfirm {
            get {
                return ResourceManager.GetString("Reservations_NoShowConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservations.
        /// </summary>
        public static string Reservations_Title {
            get {
                return ResourceManager.GetString("Reservations_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string Status_Cancelled {
            get {
                return ResourceManager.GetString("Status_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        public static string Status_Confirmed {
            get {
                return ResourceManager.GetString("Status_Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted.
        /// </summary>
        public static string Status_Converted {
            get {
                return ResourceManager.GetString("Status_Converted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No-show.
        /// </summary>
        public static string Status_NoShow {
            get {
                return ResourceManager.GetString("Status_NoShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Status_Pending {
            get {
                return ResourceManager.GetString("Status_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string Transmission_A {
            get {
                return ResourceManager.GetString("Transmission_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic 4WD.
        /// </summary>
        public static string Transmission_B {
            get {
                return ResourceManager.GetString("Transmission_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual AWD.
        /// </summary>
        public static string Transmission_C {
            get {
                return ResourceManager.GetString("Transmission_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic AWD.
        /// </summary>
        public static string Transmission_D {
            get {
                return ResourceManager.GetString("Transmission_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Automation (L5).
        /// </summary>
        public static string Transmission_F {
            get {
                return ResourceManager.GetString("Transmission_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Automation (L4).
        /// </summary>
        public static string Transmission_H {
            get {
                return ResourceManager.GetString("Transmission_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string Transmission_M {
            get {
                return ResourceManager.GetString("Transmission_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual 4WD.
        /// </summary>
        public static string Transmission_N {
            get {
                return ResourceManager.GetString("Transmission_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditional Automation (L3).
        /// </summary>
        public static string Transmission_Q {
            get {
                return ResourceManager.GetString("Transmission_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-3 Door.
        /// </summary>
        public static string Type_B {
            get {
                return ResourceManager.GetString("Type_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2/4 Door.
        /// </summary>
        public static string Type_C {
            get {
                return ResourceManager.GetString("Type_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-5 Door.
        /// </summary>
        public static string Type_D {
            get {
                return ResourceManager.GetString("Type_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupe.
        /// </summary>
        public static string Type_E {
            get {
                return ResourceManager.GetString("Type_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUV.
        /// </summary>
        public static string Type_F {
            get {
                return ResourceManager.GetString("Type_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crossover.
        /// </summary>
        public static string Type_G {
            get {
                return ResourceManager.GetString("Type_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor Home.
        /// </summary>
        public static string Type_H {
            get {
                return ResourceManager.GetString("Type_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Air All Terrain.
        /// </summary>
        public static string Type_J {
            get {
                return ResourceManager.GetString("Type_J", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial Van/Truck.
        /// </summary>
        public static string Type_K {
            get {
                return ResourceManager.GetString("Type_K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limousine/Sedan.
        /// </summary>
        public static string Type_L {
            get {
                return ResourceManager.GetString("Type_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minivan.
        /// </summary>
        public static string Type_M {
            get {
                return ResourceManager.GetString("Type_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roadster.
        /// </summary>
        public static string Type_N {
            get {
                return ResourceManager.GetString("Type_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickup (2-door).
        /// </summary>
        public static string Type_P {
            get {
                return ResourceManager.GetString("Type_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickup (4-door).
        /// </summary>
        public static string Type_Q {
            get {
                return ResourceManager.GetString("Type_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recreational Vehicle.
        /// </summary>
        public static string Type_R {
            get {
                return ResourceManager.GetString("Type_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport.
        /// </summary>
        public static string Type_S {
            get {
                return ResourceManager.GetString("Type_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convertible.
        /// </summary>
        public static string Type_T {
            get {
                return ResourceManager.GetString("Type_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passenger Van.
        /// </summary>
        public static string Type_V {
            get {
                return ResourceManager.GetString("Type_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wagon/Estate.
        /// </summary>
        public static string Type_W {
            get {
                return ResourceManager.GetString("Type_W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special.
        /// </summary>
        public static string Type_X {
            get {
                return ResourceManager.GetString("Type_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-Wheel Vehicle.
        /// </summary>
        public static string Type_Y {
            get {
                return ResourceManager.GetString("Type_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Offer Car.
        /// </summary>
        public static string Type_Z {
            get {
                return ResourceManager.GetString("Type_Z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add vehicle.
        /// </summary>
        public static string Vehicles_Add {
            get {
                return ResourceManager.GetString("Vehicles_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle created..
        /// </summary>
        public static string Vehicles_Created {
            get {
                return ResourceManager.GetString("Vehicles_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} ({1})? This cannot be undone..
        /// </summary>
        public static string Vehicles_DeleteConfirm {
            get {
                return ResourceManager.GetString("Vehicles_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle deleted..
        /// </summary>
        public static string Vehicles_Deleted {
            get {
                return ResourceManager.GetString("Vehicles_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add vehicle.
        /// </summary>
        public static string Vehicles_DialogTitle_Add {
            get {
                return ResourceManager.GetString("Vehicles_DialogTitle_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete vehicle.
        /// </summary>
        public static string Vehicles_DialogTitle_Delete {
            get {
                return ResourceManager.GetString("Vehicles_DialogTitle_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit vehicle.
        /// </summary>
        public static string Vehicles_DialogTitle_Edit {
            get {
                return ResourceManager.GetString("Vehicles_DialogTitle_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Vehicles_Field_Category {
            get {
                return ResourceManager.GetString("Vehicles_Field_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Vehicles_Field_Color {
            get {
                return ResourceManager.GetString("Vehicles_Field_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel.
        /// </summary>
        public static string Vehicles_Field_Fuel {
            get {
                return ResourceManager.GetString("Vehicles_Field_Fuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometers.
        /// </summary>
        public static string Vehicles_Field_Kilometers {
            get {
                return ResourceManager.GetString("Vehicles_Field_Kilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string Vehicles_Field_Manufacturer {
            get {
                return ResourceManager.GetString("Vehicles_Field_Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Vehicles_Field_Model {
            get {
                return ResourceManager.GetString("Vehicles_Field_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration plate.
        /// </summary>
        public static string Vehicles_Field_Plate {
            get {
                return ResourceManager.GetString("Vehicles_Field_Plate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power (kW).
        /// </summary>
        public static string Vehicles_Field_Power {
            get {
                return ResourceManager.GetString("Vehicles_Field_Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price €/day.
        /// </summary>
        public static string Vehicles_Field_PricePerDay {
            get {
                return ResourceManager.GetString("Vehicles_Field_PricePerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select manufacturer.
        /// </summary>
        public static string Vehicles_Field_SelectManufacturer {
            get {
                return ResourceManager.GetString("Vehicles_Field_SelectManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmission.
        /// </summary>
        public static string Vehicles_Field_Transmission {
            get {
                return ResourceManager.GetString("Vehicles_Field_Transmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Vehicles_Field_Type {
            get {
                return ResourceManager.GetString("Vehicles_Field_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Vehicles_Field_Year {
            get {
                return ResourceManager.GetString("Vehicles_Field_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Vehicles_Filter_Categories {
            get {
                return ResourceManager.GetString("Vehicles_Filter_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturers.
        /// </summary>
        public static string Vehicles_Filter_Manufacturers {
            get {
                return ResourceManager.GetString("Vehicles_Filter_Manufacturers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max kilometers.
        /// </summary>
        public static string Vehicles_Filter_MaxKm {
            get {
                return ResourceManager.GetString("Vehicles_Filter_MaxKm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max €/day.
        /// </summary>
        public static string Vehicles_Filter_MaxPrice {
            get {
                return ResourceManager.GetString("Vehicles_Filter_MaxPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price from (€/day).
        /// </summary>
        public static string Vehicles_Filter_PriceFrom {
            get {
                return ResourceManager.GetString("Vehicles_Filter_PriceFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price to (€/day).
        /// </summary>
        public static string Vehicles_Filter_PriceTo {
            get {
                return ResourceManager.GetString("Vehicles_Filter_PriceTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year from.
        /// </summary>
        public static string Vehicles_Filter_YearFrom {
            get {
                return ResourceManager.GetString("Vehicles_Filter_YearFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year to.
        /// </summary>
        public static string Vehicles_Filter_YearTo {
            get {
                return ResourceManager.GetString("Vehicles_Filter_YearTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string Vehicles_Filters {
            get {
                return ResourceManager.GetString("Vehicles_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Vehicles_Header_Color {
            get {
                return ResourceManager.GetString("Vehicles_Header_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Km.
        /// </summary>
        public static string Vehicles_Header_Km {
            get {
                return ResourceManager.GetString("Vehicles_Header_Km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate.
        /// </summary>
        public static string Vehicles_Header_Plate {
            get {
                return ResourceManager.GetString("Vehicles_Header_Plate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kW.
        /// </summary>
        public static string Vehicles_Header_Power {
            get {
                return ResourceManager.GetString("Vehicles_Header_Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to €/day.
        /// </summary>
        public static string Vehicles_Header_PricePerDay {
            get {
                return ResourceManager.GetString("Vehicles_Header_PricePerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        public static string Vehicles_Header_Vehicle {
            get {
                return ResourceManager.GetString("Vehicles_Header_Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Vehicles_Header_Year {
            get {
                return ResourceManager.GetString("Vehicles_Header_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicles.
        /// </summary>
        public static string Vehicles_Title {
            get {
                return ResourceManager.GetString("Vehicles_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle updated..
        /// </summary>
        public static string Vehicles_Updated {
            get {
                return ResourceManager.GetString("Vehicles_Updated", resourceCulture);
            }
        }
    }
}
